In [2]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris
data =  load_iris()

In [4]:
X = data.data
y = data.target

In [5]:
data=pd.DataFrame(X)
data['target']=y

In [6]:
data.head()

,0,1,2,3,target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [7]:
data.shape

(150, 5)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size=0.33, random_state=1)

In [9]:

from sklearn.preprocessing import StandardScaler #mean=0, sigma is 1
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [10]:
from sklearn.decomposition import PCA
pca = PCA()

In [11]:
X_train_p = pca.fit_transform(X_train)

In [12]:
X_train_p

array([[-2.13962242e+00,  5.13610868e-01,  1.99419486e-01,
        -2.31008729e-02],
       [-1.99540185e+00,  8.82301128e-01,  5.29591179e-01,
        -2.21415708e-01],
       [ 2.56560809e+00,  2.52456203e+00,  3.36324212e-01,
         2.37570906e-01],
       [ 1.88179210e+00,  6.13593714e-01,  9.89270342e-02,
        -2.09039180e-01],
       [ 2.32153724e+00,  2.67012730e-01,  7.22437857e-01,
         2.14630593e-01],
       [ 1.84467374e+00, -2.44516671e-01, -3.16505830e-01,
        -9.86626870e-02],
       [ 1.15280787e+00, -3.50084715e-01, -1.09329969e-01,
        -1.27100336e-01],
       [ 4.79050797e-01,  9.52879660e-01, -3.61253884e-01,
         1.00480704e-01],
       [ 2.91219047e+00,  1.91581270e-01,  9.30781970e-01,
         1.01054283e-01],
       [ 8.67557056e-02, -1.11609550e-01, -1.08336251e-01,
         2.25107361e-01],
       [-2.30153266e+00,  4.10609890e-01, -7.68242776e-02,
         1.23172991e-01],
       [ 1.18919390e+00, -1.19987449e+00, -6.06574629e-01,
      

In [13]:
X_test=scaler.transform(X_test)

In [14]:
X_test_p = pca.transform(X_test)


In [15]:
pca.components_ #the eigenvectors of the covariance/correlation matri

array([[ 0.539189  , -0.20375871,  0.58658648,  0.56892346],
       [ 0.28543082,  0.95620505,  0.00732108,  0.06440146],
       [ 0.74201139, -0.17785208, -0.12967908, -0.63322277],
       [-0.27789129,  0.11190588,  0.79940355, -0.52077583]])

In [18]:
pca.explained_variance_ #Eigenvalues

array([2.89368831, 0.96753367, 0.16091722, 0.01826484])

In [19]:
pca.explained_variance_ratio_ #percentage of variance captured/um of eigenvalues

array([0.71618786, 0.23946458, 0.03982701, 0.00452055])

In [20]:
pcas = PCA(n_components=0.95) #This tells PCA to automatically keep enough components to retain approximately 95% of the variance.

In [21]:
x_train_pca=pcas.fit_transform(X_train)

In [22]:
x_test_pca=pcas.transform(X_test)

In [23]:
pcas.components_

array([[ 0.539189  , -0.20375871,  0.58658648,  0.56892346],
       [ 0.28543082,  0.95620505,  0.00732108,  0.06440146]])

In [31]:
pcas.explained_variance_ #these are eigenvalues and these are pricipal components pc1,pc2

array([2.89368831, 0.96753367])

In [32]:
pcas.explained_variance_ratio_

array([0.71618786, 0.23946458])

In [33]:
retained = sum(pca.explained_variance_ratio_)

print(retained)

0.9556524398207773


In [34]:
retained = sum(pca.explained_variance_ratio_)

print(retained)

0.9556524398207773


In [35]:
lost = 1 - sum(pca.explained_variance_ratio_)

print("Information lost:", lost)

Information lost: 0.0443475601792227


In [37]:
#To see which original features contribute to each PC

In [38]:
loadings = pd.DataFrame(
    pca.components_.T,
    columns=["PC1", "PC2"],
    index=["Feature1","Feature2","Feature3","Feature4"]
)

print(loadings)

                   PC1           PC2
Feature1  1.000000e+00  4.192474e-16
Feature2 -4.192474e-16  1.000000e+00
Feature3  2.408700e-16  2.220446e-16
Feature4 -1.025345e-16  1.110223e-16
